@startuml

GtkApplication <|-- App
App *-- Project
App *-- SwankSession
App *-- Window
App *-- LispSourceNotebook
App *-- Preferences

GtkSourceView <|-- LispSourceView
LispSourceView *-- GtkSourceBuffer
LispSourceView --> Project
LispSourceView --> ProjectFile
GtkNotebook <|-- LispSourceNotebook
LispSourceNotebook "1" o-- "*" LispSourceView

Project "1" o-- "*" ProjectFile

ProjectFile *-- LispParser
ProjectFile *-- TextProvider
ProjectFile : path

GtkBox <|-- InteractionsView
InteractionsView "1" o-- "*" Interaction
InteractionsView *-- SwankSession
Interaction : expression
Interaction : result
Interaction : output
Interaction : error
SwankSession : eval(Interaction)
SwankSession : interactions
SwankSession "1" --> "*" Interaction
SwankSession *-- SwankProcess
SwankProcess *-- Process
SwankProcess : swank_fd

Process : pid
Process : in_fd
Process : out_fd
Process : err_fd

LispParser : tokens
LispParser : ast
LispParser --> TextProvider
interface TextProvider
TextProvider <|.. GtkTextProvider
TextProvider <|.. StringTextProvider
TextProvider : getChar(offset)
TextProvider : getNextOffset(offset)

@enduml
