
LIBS += gtksourceview-4
# app.c, process.c, swank_process.c, swank_session.c removed.
# Add simple_file_open.c and simple_file_save.c to SOURCES to ensure they are compiled and linked.
SOURCES += preferences.c preferences_dialog.c find_executables.c real_process.c real_swank_process.c real_swank_session.c evaluate.c interactions_view.c simple_file_open.c simple_file_save.c

include ../common/common.mk

