
LIBS += gtksourceview-4
SOURCES += swank_process.c swank_session.c evaluate.c interactions_view.c simple_file_open.c simple_file_save.c
#CFLAGS += -fprofile-arcs -ftest-coverage
#LDFLAGS += -fprofile-arcs -ftest-coverage

include ../common/common.mk

