
LIBS += gtksourceview-4
SOURCES += \
  file_open.c \
  file_new.c \
  project_new_wizard.c \
  file_save.c \
  preferences.c \
  preferences_dialog.c \
  process.c \
  real_process.c \
  swank_process.c \
  real_swank_process.c \
  real_swank_session.c \
  swank_session.c \
  evaluate.c \
  interactions_view.c \
  app.c \
  lisp_source_notebook.c \
  lisp_source_view.c \
  lisp_lexer.c \
  lisp_parser.c \
  analyser.c \
  package.c \
  package_common_lisp_user.c \
  package_common_lisp.c \
  node.c \
  lisp_parser_view.c \
  project.c \
  project_file.c \
  gtk_text_provider.c \
  string_text_provider.c \
  text_provider.c \
  asdf.c \
  asdf_view.c \
  status_bar.c \
  status_service.c

include Makefile_common

